### ISSUE TITLE
Plugin not whitelisted for Linux build

### ISSUE THREAD

**Issue by Ben-Cykyria** [minimpoun/BlueprintWebsockets#2]
Plugin will not be built for Linux (e.g. Dedicated Servers). Just add this to EasyWebsockets.uplugin:
`			"WhitelistPlatforms": [
				"Win64",
				"Win32",
				"Linux"
			]`

After that, the plugin will build, but crash. Please accept this pull request with the fix:
https://github.com/minimpoun/BlueprintWebsockets/pull/1

**Comment by minimpoun** [comment]
PR accepted
