### ISSUE TITLE
I can send messages but not receive them

### ISSUE THREAD

**Issue by xavicolomer** [minimpoun/BlueprintWebsockets#5]
HI there!

I can receive messages send from an Html page connected to the same wss, but I cannot receive any

In fact, any 'On Web Socket' event is working

Any idea / suggestion?

Thanks!

![Captura de pantalla 2022-06-25 151729](https://user-images.githubusercontent.com/1476272/175775182-01dee059-0163-40fe-8729-ab8b3b709cd3.png)

**Comment by minimpoun** [comment]
Hey @xavicolomer 

Please join the support Discord here: https://discord.com/invite/W36D96gJqX
